version: 2.1

jobs:
  build:
    resource_class: medium
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: Login to Docker
          command: docker login ghcr.io -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run:
          name: Register QEMU binary
          command: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      # Amd64
      - run:
          name: Build Docker image
          command: docker build --platform linux/amd64 -t scholzj/quarkus-multiarch-native-builder:build .
      - deploy:
          name: Tag docker image
          command: docker tag scholzj/quarkus-multiarch-native-builder:build ghcr.io/scholzj/quarkus-multiarch-native-builder:21-amd64
      - deploy:
          name: Push Docker image
          command: docker push ghcr.io/scholzj/quarkus-multiarch-native-builder:21-amd64
      - deploy:
          name: Amend manifest
          command: docker manifest create ghcr.io/scholzj/quarkus-multiarch-native-builder:21 --amend ghcr.io/scholzj/quarkus-multiarch-native-builder:21-amd64
      - deploy:
          name: Tag docker image
          command: docker tag scholzj/quarkus-multiarch-native-builder:build ghcr.io/scholzj/quarkus-multiarch-native-builder:latest-amd64
      - deploy:
          name: Push Docker image
          command: docker push ghcr.io/scholzj/quarkus-multiarch-native-builder:latest-amd64
      - deploy:
          name: Amend manifest
          command: docker manifest create ghcr.io/scholzj/quarkus-multiarch-native-builder:latest --amend ghcr.io/scholzj/quarkus-multiarch-native-builder:latest-amd64
      # Arm64
      - run:
          name: Build Docker image
          command: docker build --platform linux/arm64 -t scholzj/quarkus-multiarch-native-builder:build .
      - deploy:
          name: Tag docker image
          command: docker tag scholzj/quarkus-multiarch-native-builder:build ghcr.io/scholzj/quarkus-multiarch-native-builder:21-arm64
      - deploy:
          name: Push Docker image
          command: docker push ghcr.io/scholzj/quarkus-multiarch-native-builder:21-arm64
      - deploy:
          name: Amend manifest
          command: docker manifest create ghcr.io/scholzj/quarkus-multiarch-native-builder:21 --amend ghcr.io/scholzj/quarkus-multiarch-native-builder:21-arm64
      - deploy:
          name: Tag docker image
          command: docker tag scholzj/quarkus-multiarch-native-builder:build ghcr.io/scholzj/quarkus-multiarch-native-builder:latest-arm64
      - deploy:
          name: Push Docker image
          command: docker push ghcr.io/scholzj/quarkus-multiarch-native-builder:latest-arm64
      - deploy:
          name: Amend manifest
          command: docker manifest create ghcr.io/scholzj/quarkus-multiarch-native-builder:latest --amend ghcr.io/scholzj/quarkus-multiarch-native-builder:latest-arm64
      # Push manifests
      - deploy:
          name: Push manifest
          command: docker manifest push ghcr.io/scholzj/quarkus-multiarch-native-builder:latest
      - deploy:
          name: Push manifest
          command: docker manifest push ghcr.io/scholzj/quarkus-multiarch-native-builder:21

workflows:
  build-workflow:
    jobs:
      - build:
          context: ghcr.io